Итоговая

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -79,10 +79,14 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Login to Docker Hub
-        if: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN != '' && secrets.DOCKER_HUB_USERNAME != '' }}
         run: |
+          if [ -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ] || [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
+            echo "Error: DOCKER_HUB_ACCESS_TOKEN or DOCKER_HUB_USERNAME is missing!"
+            exit 1
+          fi
           echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | \
           docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
+      
 
       - name: Login in DockerHub
         run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
